"""
Base strategy class that all trading strategies must extend.
"""
from abc import ABC, abstractmethod
import pandas as pd
from typing import Dict, Any, List
from dataclasses import dataclass, asdict
import logging

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """
    Trading signal dataclass.

    Represents a buy/sell/hold signal generated by a strategy.
    """
    date: str  # ISO format date string
    signal_type: str  # BUY, SELL, HOLD
    price: float  # Price at signal
    confidence: float  # Confidence score (0-100)
    metadata: Dict[str, Any]  # Strategy-specific data

    def to_dict(self) -> dict:
        """Convert signal to dictionary."""
        return asdict(self)

    def __repr__(self):
        return f"Signal({self.signal_type} at ₹{self.price:.2f} on {self.date}, confidence={self.confidence}%)"


class BaseStrategy(ABC):
    """
    Base class for all trading strategies.

    All strategies must implement:
    1. analyze() - Generate trading signals
    2. get_default_params() - Return default parameters

    Strategies can override:
    - validate_data() - Custom data validation
    - get_description() - Strategy description
    """

    def __init__(self, **params):
        """
        Initialize strategy with parameters.

        Args:
            **params: Strategy-specific parameters
        """
        self.name = self.__class__.__name__
        self.default_params = self.get_default_params()
        self.params = {**self.default_params, **params}  # Merge defaults with overrides
        self.signals: List[Signal] = []

        logger.debug(f"Initialized {self.name} with params: {self.params}")

    @abstractmethod
    def analyze(self, data: pd.DataFrame) -> List[Signal]:
        """
        Analyze data and generate trading signals.

        Args:
            data: DataFrame with OHLCV data (must have: open, high, low, close, volume)

        Returns:
            List of Signal objects

        Raises:
            ValueError: If data format is invalid
        """
        pass

    @abstractmethod
    def get_default_params(self) -> Dict[str, Any]:
        """
        Return default parameters for the strategy.

        Returns:
            Dictionary of parameter names and default values

        Example:
            {
                'period': 14,
                'threshold': 30
            }
        """
        pass

    def validate_data(self, data: pd.DataFrame) -> bool:
        """
        Validate that input data has required columns.

        Args:
            data: DataFrame to validate

        Returns:
            True if valid, False otherwise
        """
        required = ['open', 'high', 'low', 'close', 'volume']
        missing = [col for col in required if col not in data.columns]

        if missing:
            logger.error(f"{self.name}: Missing required columns: {missing}")
            return False

        if data.empty:
            logger.error(f"{self.name}: DataFrame is empty")
            return False

        return True

    def get_signals(self) -> List[Signal]:
        """
        Get all generated signals.

        Returns:
            List of Signal objects
        """
        return self.signals

    def get_latest_signal(self) -> Signal:
        """
        Get the most recent signal.

        Returns:
            Latest Signal object or None if no signals
        """
        return self.signals[-1] if self.signals else None

    def get_signal_count(self) -> Dict[str, int]:
        """
        Get count of each signal type.

        Returns:
            Dictionary with counts of BUY, SELL, HOLD signals
        """
        counts = {'BUY': 0, 'SELL': 0, 'HOLD': 0}

        for signal in self.signals:
            if signal.signal_type in counts:
                counts[signal.signal_type] += 1

        return counts

    def get_description(self) -> str:
        """
        Get strategy description.

        Returns:
            Human-readable description of the strategy

        Override this in subclasses for better documentation.
        """
        return f"{self.name} trading strategy"

    def reset(self):
        """Clear all generated signals."""
        self.signals = []
        logger.debug(f"{self.name}: Signals reset")

    def __repr__(self):
        return f"<{self.name}(params={self.params})>"

    def __str__(self):
        return f"{self.name} Strategy"
