
-- Indian Stock Market Analysis Database Schema
-- PostgreSQL with TimescaleDB Extension

-- Enable TimescaleDB extension
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

-- Stock master table
CREATE TABLE IF NOT EXISTS stocks (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    sector VARCHAR(100),
    industry VARCHAR(100),
    exchange VARCHAR(10) NOT NULL,  -- NSE, BSE
    isin VARCHAR(20),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE stocks IS 'Master table for all stocks';
COMMENT ON COLUMN stocks.exchange IS 'Stock exchange: NSE or BSE';

-- Time-series price data (will be converted to TimescaleDB hypertable)
CREATE TABLE IF NOT EXISTS stock_prices (
    id BIGSERIAL,
    stock_id INTEGER NOT NULL REFERENCES stocks(id) ON DELETE CASCADE,
    date TIMESTAMP NOT NULL,
    open DECIMAL(12, 2) NOT NULL,
    high DECIMAL(12, 2) NOT NULL,
    low DECIMAL(12, 2) NOT NULL,
    close DECIMAL(12, 2) NOT NULL,
    volume BIGINT NOT NULL,
    adj_close DECIMAL(12, 2),
    source VARCHAR(50),  -- Data source: yahoo, nse, upstox, etc.
    PRIMARY KEY (stock_id, date)
);

COMMENT ON TABLE stock_prices IS 'Historical stock price data (OHLCV)';

-- Convert to TimescaleDB hypertable
SELECT create_hypertable('stock_prices', 'date', if_not_exists => TRUE);

-- Create indexes on stock_prices
CREATE INDEX IF NOT EXISTS idx_stock_prices_stock_date ON stock_prices(stock_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_stock_prices_date ON stock_prices(date DESC);
CREATE INDEX IF NOT EXISTS idx_stock_prices_source ON stock_prices(source);

-- Strategy signals
CREATE TABLE IF NOT EXISTS signals (
    id SERIAL PRIMARY KEY,
    stock_id INTEGER NOT NULL REFERENCES stocks(id) ON DELETE CASCADE,
    strategy_name VARCHAR(100) NOT NULL,
    signal_type VARCHAR(20) NOT NULL,  -- BUY, SELL, HOLD
    signal_date TIMESTAMP NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    confidence DECIMAL(5, 2),  -- 0-100
    signal_metadata JSONB,  -- Store strategy-specific data (renamed to avoid SQLAlchemy conflict)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE signals IS 'Trading signals generated by strategies';
COMMENT ON COLUMN signals.signal_metadata IS 'Strategy-specific parameters and values';

-- Create indexes on signals
CREATE INDEX IF NOT EXISTS idx_signals_stock_date ON signals(stock_id, signal_date DESC);
CREATE INDEX IF NOT EXISTS idx_signals_date ON signals(signal_date DESC);
CREATE INDEX IF NOT EXISTS idx_signals_strategy ON signals(strategy_name);
CREATE INDEX IF NOT EXISTS idx_signals_type ON signals(signal_type);

-- Backtest results
CREATE TABLE IF NOT EXISTS backtest_results (
    id SERIAL PRIMARY KEY,
    strategy_name VARCHAR(100) NOT NULL,
    stock_id INTEGER NOT NULL REFERENCES stocks(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    initial_capital DECIMAL(15, 2) NOT NULL,
    final_capital DECIMAL(15, 2) NOT NULL,
    total_return DECIMAL(15, 2),
    total_return_pct DECIMAL(10, 2),
    total_trades INTEGER,
    winning_trades INTEGER,
    losing_trades INTEGER,
    win_rate DECIMAL(5, 2),
    avg_profit DECIMAL(12, 2),
    avg_loss DECIMAL(12, 2),
    max_profit DECIMAL(12, 2),
    max_loss DECIMAL(12, 2),
    sharpe_ratio DECIMAL(10, 4),
    max_drawdown DECIMAL(10, 2),
    backtest_metadata JSONB,  -- Store additional metrics and parameters (renamed to avoid SQLAlchemy conflict)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE backtest_results IS 'Backtesting results for strategies';

-- Create indexes on backtest_results
CREATE INDEX IF NOT EXISTS idx_backtest_strategy ON backtest_results(strategy_name);
CREATE INDEX IF NOT EXISTS idx_backtest_stock ON backtest_results(stock_id);
CREATE INDEX IF NOT EXISTS idx_backtest_date_range ON backtest_results(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_backtest_created ON backtest_results(created_at DESC);

-- FII/DII Data (Foreign and Domestic Institutional Investment)
-- Unique to Indian markets - shows institutional money flow
CREATE TABLE IF NOT EXISTS fii_dii_data (
    id SERIAL PRIMARY KEY,
    date DATE UNIQUE NOT NULL,
    fii_gross_purchase DECIMAL(12, 2) DEFAULT 0.0,
    fii_gross_sale DECIMAL(12, 2) DEFAULT 0.0,
    fii_net DECIMAL(12, 2) DEFAULT 0.0,
    dii_gross_purchase DECIMAL(12, 2) DEFAULT 0.0,
    dii_gross_sale DECIMAL(12, 2) DEFAULT 0.0,
    dii_net DECIMAL(12, 2) DEFAULT 0.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE fii_dii_data IS 'FII/DII institutional investment data from NSE (in Crores)';
COMMENT ON COLUMN fii_dii_data.fii_net IS 'FII net flow: Positive = buying, Negative = selling';
COMMENT ON COLUMN fii_dii_data.dii_net IS 'DII net flow: Positive = buying, Negative = selling';

-- Create indexes on fii_dii_data
CREATE INDEX IF NOT EXISTS idx_fii_dii_date ON fii_dii_data(date DESC);

-- Delivery Data (shows genuine buying vs speculation)
-- Unique to Indian markets - available from NSE
CREATE TABLE IF NOT EXISTS delivery_data (
    id SERIAL PRIMARY KEY,
    stock_id INTEGER NOT NULL REFERENCES stocks(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    delivery_quantity BIGINT DEFAULT 0,
    traded_quantity BIGINT DEFAULT 0,
    delivery_percentage DECIMAL(5, 2) DEFAULT 0.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(stock_id, date)
);

COMMENT ON TABLE delivery_data IS 'Delivery percentage data from NSE';
COMMENT ON COLUMN delivery_data.delivery_percentage IS 'Delivery %: >60% = genuine buying, <40% = speculation';

-- Create indexes on delivery_data
CREATE INDEX IF NOT EXISTS idx_delivery_stock_date ON delivery_data(stock_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_delivery_date ON delivery_data(date DESC);
CREATE INDEX IF NOT EXISTS idx_delivery_percentage ON delivery_data(delivery_percentage);

-- User watchlists (for future use)
CREATE TABLE IF NOT EXISTS watchlists (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE watchlists IS 'User-created stock watchlists';

-- Watchlist stocks mapping
CREATE TABLE IF NOT EXISTS watchlist_stocks (
    id SERIAL PRIMARY KEY,
    watchlist_id INTEGER NOT NULL REFERENCES watchlists(id) ON DELETE CASCADE,
    stock_id INTEGER NOT NULL REFERENCES stocks(id) ON DELETE CASCADE,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(watchlist_id, stock_id)
);

COMMENT ON TABLE watchlist_stocks IS 'Stocks in each watchlist';

-- Create indexes on watchlist tables
CREATE INDEX IF NOT EXISTS idx_watchlist_stocks_watchlist ON watchlist_stocks(watchlist_id);
CREATE INDEX IF NOT EXISTS idx_watchlist_stocks_stock ON watchlist_stocks(stock_id);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
CREATE TRIGGER update_stocks_updated_at
    BEFORE UPDATE ON stocks
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_watchlists_updated_at
    BEFORE UPDATE ON watchlists
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Insert default watchlist (NIFTY 50)
INSERT INTO watchlists (name, description)
VALUES ('NIFTY 50', 'India''s benchmark stock market index')
ON CONFLICT DO NOTHING;

-- View for latest stock prices
CREATE OR REPLACE VIEW latest_stock_prices AS
SELECT DISTINCT ON (stock_id)
    stock_id,
    date,
    open,
    high,
    low,
    close,
    volume,
    adj_close,
    source
FROM stock_prices
ORDER BY stock_id, date DESC;

COMMENT ON VIEW latest_stock_prices IS 'Latest price for each stock';

-- View for stock summary with latest price
CREATE OR REPLACE VIEW stock_summary AS
SELECT
    s.id,
    s.symbol,
    s.name,
    s.sector,
    s.industry,
    s.exchange,
    lsp.close AS latest_price,
    lsp.date AS price_date,
    lsp.volume AS latest_volume
FROM stocks s
LEFT JOIN latest_stock_prices lsp ON s.id = lsp.stock_id
WHERE s.is_active = true;

COMMENT ON VIEW stock_summary IS 'Stock master data with latest price';

-- Grant permissions (adjust as needed)
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO your_user;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO your_user;
