"""
SQLAlchemy database models for stock market analysis.

Compatible with both SQLite and PostgreSQL.
"""
from sqlalchemy import (
    Column, Integer, String, Float, BigInteger,
    DateTime, Date, Boolean, ForeignKey, Index, Text
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.types import JSON
from datetime import datetime
import json

Base = declarative_base()


class Stock(Base):
    """Stock master table."""
    __tablename__ = 'stocks'

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), unique=True, nullable=False, index=True)
    name = Column(String(255), nullable=False)
    sector = Column(String(100))
    industry = Column(String(100))
    exchange = Column(String(10), nullable=False)  # NSE, BSE
    isin = Column(String(20))
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    prices = relationship("StockPrice", back_populates="stock", cascade="all, delete-orphan")
    signals = relationship("Signal", back_populates="stock", cascade="all, delete-orphan")
    backtest_results = relationship("BacktestResult", back_populates="stock", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Stock(symbol='{self.symbol}', name='{self.name}')>"


class StockPrice(Base):
    """Time-series stock price data."""
    __tablename__ = 'stock_prices'

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    stock_id = Column(Integer, ForeignKey('stocks.id', ondelete='CASCADE'), nullable=False)
    date = Column(DateTime, nullable=False, index=True)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(BigInteger, nullable=False)
    adj_close = Column(Float)
    source = Column(String(50))  # yahoo, nse, upstox

    # Relationship
    stock = relationship("Stock", back_populates="prices")

    __table_args__ = (
        Index('idx_stock_prices_stock_date', 'stock_id', 'date'),
        Index('idx_stock_prices_date', 'date'),
        Index('idx_stock_prices_source', 'source'),
    )

    def __repr__(self):
        return f"<StockPrice(stock_id={self.stock_id}, date='{self.date}', close={self.close})>"


class Signal(Base):
    """Trading signals generated by strategies."""
    __tablename__ = 'signals'

    id = Column(Integer, primary_key=True, autoincrement=True)
    stock_id = Column(Integer, ForeignKey('stocks.id', ondelete='CASCADE'), nullable=False)
    strategy_name = Column(String(100), nullable=False, index=True)
    signal_type = Column(String(20), nullable=False, index=True)  # BUY, SELL, HOLD
    signal_date = Column(DateTime, nullable=False, index=True)
    price = Column(Float, nullable=False)
    confidence = Column(Float)  # 0-100
    signal_metadata = Column(JSON)  # SQLite uses JSON, PostgreSQL uses JSONB
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationship
    stock = relationship("Stock", back_populates="signals")

    __table_args__ = (
        Index('idx_signals_stock_date', 'stock_id', 'signal_date'),
        Index('idx_signals_date', 'signal_date'),
        Index('idx_signals_strategy', 'strategy_name'),
        Index('idx_signals_type', 'signal_type'),
    )

    def to_dict(self):
        """Convert to dictionary."""
        return {
            'id': self.id,
            'stock_id': self.stock_id,
            'strategy_name': self.strategy_name,
            'signal_type': self.signal_type,
            'signal_date': self.signal_date.isoformat() if self.signal_date else None,
            'price': self.price,
            'confidence': self.confidence,
            'metadata': self.signal_metadata,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }

    def __repr__(self):
        return f"<Signal(stock_id={self.stock_id}, type='{self.signal_type}', strategy='{self.strategy_name}')>"


class BacktestResult(Base):
    """Backtesting results for strategies."""
    __tablename__ = 'backtest_results'

    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_name = Column(String(100), nullable=False, index=True)
    stock_id = Column(Integer, ForeignKey('stocks.id', ondelete='CASCADE'), nullable=False)
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    initial_capital = Column(Float, nullable=False)
    final_capital = Column(Float, nullable=False)
    total_return = Column(Float)
    total_return_pct = Column(Float)
    total_trades = Column(Integer)
    winning_trades = Column(Integer)
    losing_trades = Column(Integer)
    win_rate = Column(Float)
    avg_profit = Column(Float)
    avg_loss = Column(Float)
    max_profit = Column(Float)
    max_loss = Column(Float)
    sharpe_ratio = Column(Float)
    max_drawdown = Column(Float)
    backtest_metadata = Column(JSON)  # SQLite uses JSON, PostgreSQL uses JSONB
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationship
    stock = relationship("Stock", back_populates="backtest_results")

    __table_args__ = (
        Index('idx_backtest_strategy', 'strategy_name'),
        Index('idx_backtest_stock', 'stock_id'),
        Index('idx_backtest_date_range', 'start_date', 'end_date'),
        Index('idx_backtest_created', 'created_at'),
    )

    def to_dict(self):
        """Convert to dictionary."""
        return {
            'id': self.id,
            'strategy_name': self.strategy_name,
            'stock_id': self.stock_id,
            'start_date': self.start_date.isoformat() if self.start_date else None,
            'end_date': self.end_date.isoformat() if self.end_date else None,
            'initial_capital': self.initial_capital,
            'final_capital': self.final_capital,
            'total_return': self.total_return,
            'total_return_pct': self.total_return_pct,
            'total_trades': self.total_trades,
            'winning_trades': self.winning_trades,
            'losing_trades': self.losing_trades,
            'win_rate': self.win_rate,
            'avg_profit': self.avg_profit,
            'avg_loss': self.avg_loss,
            'max_profit': self.max_profit,
            'max_loss': self.max_loss,
            'sharpe_ratio': self.sharpe_ratio,
            'max_drawdown': self.max_drawdown,
            'metadata': self.backtest_metadata,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }

    def __repr__(self):
        return f"<BacktestResult(strategy='{self.strategy_name}', stock_id={self.stock_id}, return={self.total_return_pct}%)>"


class FIIDIIData(Base):
    """FII/DII institutional investment data (India-specific)."""
    __tablename__ = 'fii_dii_data'

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, unique=True, nullable=False, index=True)
    fii_gross_purchase = Column(Float, default=0.0)
    fii_gross_sale = Column(Float, default=0.0)
    fii_net = Column(Float, default=0.0)
    dii_gross_purchase = Column(Float, default=0.0)
    dii_gross_sale = Column(Float, default=0.0)
    dii_net = Column(Float, default=0.0)
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        Index('idx_fii_dii_date', 'date'),
    )

    def __repr__(self):
        return f"<FIIDIIData(date='{self.date}', fii_net={self.fii_net}, dii_net={self.dii_net})>"


class DeliveryData(Base):
    """Delivery percentage data (India-specific)."""
    __tablename__ = 'delivery_data'

    id = Column(Integer, primary_key=True, autoincrement=True)
    stock_id = Column(Integer, ForeignKey('stocks.id', ondelete='CASCADE'), nullable=False)
    date = Column(Date, nullable=False)
    delivery_quantity = Column(BigInteger, default=0)
    traded_quantity = Column(BigInteger, default=0)
    delivery_percentage = Column(Float, default=0.0)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationship
    stock = relationship("Stock")

    __table_args__ = (
        Index('idx_delivery_stock_date', 'stock_id', 'date'),
        Index('idx_delivery_date', 'date'),
        Index('idx_delivery_percentage', 'delivery_percentage'),
    )

    def __repr__(self):
        return f"<DeliveryData(stock_id={self.stock_id}, date='{self.date}', delivery_pct={self.delivery_percentage})>"
