"""
Signal model for SQLAlchemy ORM.
"""
from sqlalchemy import Column, Integer, String, DateTime, Numeric, ForeignKey, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from .base import Base


class Signal(Base):
    """Trading signals generated by strategies."""

    __tablename__ = 'signals'

    id = Column(Integer, primary_key=True, autoincrement=True)
    stock_id = Column(Integer, ForeignKey('stocks.id', ondelete='CASCADE'), nullable=False)
    strategy_name = Column(String(100), nullable=False)
    signal_type = Column(String(20), nullable=False)  # BUY, SELL, HOLD
    signal_date = Column(DateTime, nullable=False)
    price = Column(Numeric(12, 2), nullable=False)
    confidence = Column(Numeric(5, 2))  # 0-100
    metadata = Column(JSONB)  # Strategy-specific data
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    stock = relationship("Stock", back_populates="signals")

    def __repr__(self):
        return f"<Signal(stock_id={self.stock_id}, strategy='{self.strategy_name}', type='{self.signal_type}', date='{self.signal_date}')>"

    def to_dict(self):
        """Convert model to dictionary."""
        return {
            'id': self.id,
            'stock_id': self.stock_id,
            'strategy_name': self.strategy_name,
            'signal_type': self.signal_type,
            'signal_date': self.signal_date.isoformat() if self.signal_date else None,
            'price': float(self.price) if self.price else None,
            'confidence': float(self.confidence) if self.confidence else None,
            'metadata': self.metadata,
            'created_at': self.created_at.isoformat() if self.created_at else None,
        }
